name: Package Scanner Lambda

on:
  push:
    tags:
      - 'scanner-v*'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-package-lambda.yml
    with:
      lambda-name: 'scanner'
      lambda-path: 'lambdas/functions/iroco2-client-side-scanner'
      handler-dir: 'package'
    secrets: inherit
